# EXERCISE 1

In [69]:
import pandas as pd

In [70]:
import scipy.stats as stats

In [71]:
# Data for Unit A and Unit B
data = {
    'Unit A': [6.809, 6.4376, 6.9157, 7.3012, 7.4488, 7.3871, 6.8755, 7.0621, 6.684, 6.8236, 7.393, 7.5169, 6.9246, 6.9256, 6.5797, 6.8394, 6.597, 7.2705, 7.2828, 7.3495, 6.9438, 7.156, 6.5341, 7.2854, 6.9952, 6.8568, 7.2163, 6.6801, 6.9431, 7.0852, 6.7794, 7.2783, 7.1561, 7.3943, 6.9405],
    'Unit B': [6.7703, 7.5093, 6.73, 6.7878, 7.1522, 6.811, 7.2212, 6.6606, 7.2402, 7.0503, 6.881, 7.4059, 6.7652, 6.038, 7.1581, 7.024, 6.6672, 7.4314, 7.307, 6.7478, 6.8889, 7.422, 6.5217, 7.1688, 6.7594, 6.9399, 7.0133, 6.9182, 6.3346, 7.5459, 7.0992, 7.118, 6.6965, 6.578, 7.3875]
}

In [72]:
# Convert to DataFrame
df = pd.DataFrame(data)



In [73]:
# Display the first few rows of the DataFrame
df.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [74]:
# Perform two-sample t-test
t_statistic, p_value = stats.ttest_ind(df['Unit A'], df['Unit B'])

In [75]:
# Display the results
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")

T-statistic: 0.7228688704678063
P-value: 0.4722394724599501


In [76]:
# Conclusion
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference in the mean diameters.")
else:
    print("Fail to reject the null hypothesis: There is no significant difference in the mean diameters.")

Fail to reject the null hypothesis: There is no significant difference in the mean diameters.


In [77]:
# Normality test for Unit A
shapiro_A = stats.shapiro(df['Unit A'])
print(f"Shapiro-Wilk test for Unit A: {shapiro_A}")

# Normality test for Unit B
shapiro_B = stats.shapiro(df['Unit B'])
print(f"Shapiro-Wilk test for Unit B: {shapiro_B}")


Shapiro-Wilk test for Unit A: ShapiroResult(statistic=0.9649459719657898, pvalue=0.31998491287231445)
Shapiro-Wilk test for Unit B: ShapiroResult(statistic=0.9727305769920349, pvalue=0.5225146412849426)


In [78]:
# F-test for equality of variances
levene_test = stats.levene(df['Unit A'], df['Unit B'])
print(f"Levene's test for equality of variances: {levene_test}")


Levene's test for equality of variances: LeveneResult(statistic=0.6650897638632386, pvalue=0.4176162212502553)


In [79]:
#After conducting a thorough hypothesis test to compare the diameters of cutlets between Unit A and Unit B, we conclude that there is no significant difference in the mean diameters of the cutlets between the two units at the 5% significance level. The assumptions of normality and equality of variances were validated, supporting the robustness of our test results.

# EXERCISE 2

In [93]:
import pandas as pd

In [94]:
import scipy.stats as stats

In [95]:
data = df

In [96]:
df = pd.read_csv(r"C:\Users\Acer\Desktop\Data Sci Assignments\Hypothesis Testing\LabTAT.csv")

In [97]:
data.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [98]:
stats.f_oneway(df['Laboratory 1'],df['Laboratory 2'],df['Laboratory 3'],df['Laboratory 4'])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [99]:
alpha = 0.05  # significance level

if p_value < alpha:
    print("Reject the null hypothesis (H0). There is a significant difference in the average TAT among the laboratories.")
else:
    print("Fail to reject the null hypothesis (H0). There is no significant difference in the average TAT among the laboratories.")

Fail to reject the null hypothesis (H0). There is no significant difference in the average TAT among the laboratories.


# EXERCISE 3

In [101]:
import numpy as np
from scipy.stats import chi2_contingency

# Define the observed values
observed = np.array([[50, 142, 131, 70],
                     [550, 351, 480, 350]])

# Perform chi-square test
chi2, p, dof, expected = chi2_contingency(observed)

# Print results
print("Chi-square statistic:", chi2)
print("P-value:", p)
print("Degrees of freedom:", dof)
print("Expected frequencies:")
print(expected)

# Define significance level (alpha)
alpha = 0.05

# Decision based on p-value
if p < alpha:
    print(f"Since p-value ({p}) < alpha ({alpha}), we reject the null hypothesis.")
else:
    print(f"Since p-value ({p}) >= alpha ({alpha}), we fail to reject the null hypothesis.")


Chi-square statistic: 80.27295426602495
P-value: 2.682172557281901e-17
Degrees of freedom: 3
Expected frequencies:
[[111.01694915  91.21892655 113.05225989  77.71186441]
 [488.98305085 401.78107345 497.94774011 342.28813559]]
Since p-value (2.682172557281901e-17) < alpha (0.05), we reject the null hypothesis.


# EXERCISE 4

In [65]:
import numpy as np
from scipy.stats import chi2_contingency

# Define the observed data
observed = np.array([[87, 13],
                     [88, 12],
                     [80, 20],
                     [84, 16]])

# Perform chi-square test of independence
chi2, p, dof, expected = chi2_contingency(observed)

# Output the results
print("Chi-square statistic:", chi2)
print("P-value:", p)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)


Chi-square statistic: 2.9982107452004447
P-value: 0.3919011264406871
Degrees of freedom: 3
Expected frequencies:
 [[84.75 15.25]
 [84.75 15.25]
 [84.75 15.25]
 [84.75 15.25]]


In [66]:
alpha = 0.05

# Decision-making
if p < alpha:
    print("\nReject the null hypothesis.")
    print("There is a significant association between center and defective order forms.")
else:
    print("\nFail to reject the null hypothesis.")
    print("There is no significant association between center and defective order forms.")


Fail to reject the null hypothesis.
There is no significant association between center and defective order forms.
